In [3]:
import numpy as np

In [6]:
# there is another method in numpy to create an ideintity matrix

a = np.identity(4,dtype=int)
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

**conversion of 1D array to 2D array**

# 1. resize- parmnt
# 2. reshape - temp.
# 3. ravel - temp (nd array to 1 dim)

In [14]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
a.ndim

1

In [16]:
a.shape

(16,)

In [17]:
a.size

16

In [24]:
# resize(rows,columns) permanent to 4 rows and column
a.resize((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
a.ndim
a.shape # permanent to 2 dimension

(4, 4)

In [26]:
a.resize((8,2))
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [27]:
a.shape

(8, 2)

In [29]:
a.reshape(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
a.reshape((2,8)) #this is temp method ,here shpae is 2,8

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [33]:
a.shape # again when shape is called ,it returns shape modify by permanent method

(8, 2)

In [34]:
# when user want to convert an ND array to 1D always (TEMP.)
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# transpose:
it is temp method  
2 ways: transpose() , a.T

        



In [35]:
a # shape 8*2


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [36]:
a.transpose() # shape 2*8

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

In [37]:
a.T

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

In [38]:
a.shape # originl 8 *2

(8, 2)

In [39]:
#another way to transpose
x = np.arange(22).reshape((11,2))
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [40]:
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [ ]:
# Assigment
# 1. add a number in 1D array
# 2. add a row in 2D array
# 3. add a column in 2D array
# 4. remove a number from 1D array
# 5. remove a row from 2D array
# 6. remove a column from 2D array
# 7. Concatenate 2 arrays

In [43]:
p = np.arange(11)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
np.append(p,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
arr = np.array([[1,2,3],
                [4,5,6]])

new_row = [7,8,9]

new_arr = np.append(arr, [new_row], axis=0)

print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
arr = np.array([[1,2,3],
                [4,5,6]])

new_col = [[7],
           [8]]

new_arr = np.append(arr, new_col, axis=1)

print(new_arr)

[[1 2 3 7]
 [4 5 6 8]]


In [66]:
arr = np.array([1, 2, 3, 4])

# remove element at index 2 (value 3)
new_arr = np.delete(arr, 2)

print(new_arr)

[1 2 4]


In [67]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

# remove row index 1
new_arr = np.delete(arr, 1, axis=0)

print(new_arr)

[[1 2 3]
 [7 8 9]]


In [68]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

# remove column index 1
new_arr = np.delete(arr, 1, axis=1)

print(new_arr)

[[1 3]
 [4 6]
 [7 9]]


In [69]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate((a,b))

print(c)

[1 2 3 4 5 6]
