**DATA SCIENCE NUMPY PRACTICE**

In [2]:
#import library
import numpy as np

In [4]:
np.__version__

'2.1.3'

In [16]:
#create numpy array
a = np.array([10,20,30,40])
a


array([10, 20, 30, 40])

difference between list and numpy array:

list is built in | numpy is external lib

list dosent support mathematical operation| support mathematical operation

list contain values with diff dtype| numpy array contain same dtype element

dont support multidimensionality or it is messy| support 2D 3D multidimensional array

less powerful | more powerful








**data type hierarchy**:

precedence to data type:

string(object)>complex>float>int

if we have change any value of int array to float then all array values will convert to float


In [18]:
#value converted to float . float>int
np.array([10,20,30,40.])


array([10., 20., 30., 40.])

**bold text**

In [11]:
#all float values converted to complex values
np.array([10,20,(30+4j),40.])

array([10.+0.j, 20.+0.j, 30.+4.j, 40.+0.j])

In [12]:
#all values are converted to strings
c = np.array([10,20,(30+4j),40.,'A'])

array(['10', '20', '(30+4j)', '40.0', 'A'], dtype='<U64')

**Different ways to create numpy arrays:**

usibg **arange**,**zeros**(with default dtype is float and flexibility to change dtype),**ones**(with default dtype is float and flexibility to change dtype)

In [24]:
np.arange(20)  #stop--> exclusive

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
np.arange(5,10)  # start,stop

array([5, 6, 7, 8, 9])

In [28]:
np.arange(1,30,2) # start ,stop ,step : so odd numbers: stop exclusive

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [34]:
np.zeros(10,dtype=bool)

array([False, False, False, False, False, False, False, False, False,
       False])

In [36]:
np.zeros(10,dtype=complex)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

In [39]:
b = np.zeros(10,dtype=int)  # 1D array a single row
b


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
b.ndim

1

In [47]:
c = np.zeros((5,6)) # 2D array rows and columns . collection of 1D array
c

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [48]:
c.ndim

2

In [49]:
np.zeros((4,5,6))  # 3D array: 4 blocks,5 rows, 6 columns \\ collection of 2D arrays

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [52]:
# Create an array of constant number
#np.full(shape,fill_value)
np.full((4,5),2) # 4 rows, 5 columns with all 2

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [ ]:
# Create 4x4 array of all True values
# Create 4x4 array of all False values
# Create 4x4 array of Digonal elements as 1's and Non diagonal elements as 0's
# Create 4x4 array of Digonal elements as True and Non diagonal elements as False
# Create 4x4 array of Digonal elements as False and Non diagonal elements as True
# Assignment: Create 2D and 3D arrays of 1's

In [54]:
# Create 4x4 array of all True values
#sol 1
np.ones((4,4), dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [60]:
#sol 2
np.full((4,4),1,dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [57]:
#Create 4x4 array of all False values
#sol 1
np.full((4,4),0,dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [55]:
#sol 2
np.zeros((4,4), dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [64]:
#Create 4x4 array of Digonal elements as 1 and Non diagonal elements as 0
np.eye(4,4,0,dtype=int) #eye():== n=no rows,m=no of column,k=index of diagonal

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [66]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [67]:
#Create 4x4 array of Digonal elements as True and Non diagonal elements as False
np.eye(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [68]:
np.eye(4,k=1,dtype=bool)

array([[False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [69]:
~np.eye(4,dtype=bool)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [72]:
#Create 2D and 3D arrays of 1's
np.ones((4,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [73]:
np.ones((5,4,3),dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])